export const actionTypes = {
  CREATE: "CREATE",
  READ: "READ",
  UPDATE: "UPDATE",
  DELETE_SELECTED: "DELETE_SELECTED",
  DELETE_ALL: "DELETE_ALL",
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
  PENDING: "PENDING"
}